//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamuiFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YamuiFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1, h2, h3 { color: navy; font-weight:normal; }
        ///h1 { margin-bottom: .47em }
        ///h2 { margin-bottom: .3em }
        ///h3 { margin-bottom: .4em }
        ///ul { margin-top: .5em }
        ///ul li {margin: .25em}
        ////* special for Yamui */ 
        ///body {
        ///    Font: 12px SEGOEUI;
        ///    color: %FormForeGroundColor%;
        ///}
        ///a:hover { text-decoration: underline; }
        ///pre  { border:solid 1px gray; background-color:#eee; padding:1em }
        ///a:link { text-decoration: none; }
        ///.gray    { color:gray; }
        ///.example { background-color:#efefef; corner-radius:5px; padding [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baseCss {
            get {
                return ResourceManager.GetString("baseCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;Item&gt;
        ///    &lt;ThemeName Value=&quot;Classique theme&quot; /&gt;
        ///    &lt;FormColorBackColor Value=&quot;#E6E6E6&quot; /&gt;
        ///    &lt;FormColorForeColor Value=&quot;#1E1E1E&quot; /&gt;
        ///    &lt;ScrollBarsColorsNormalBackColor Value=&quot;#CCCCCC&quot; /&gt;
        ///    &lt;ScrollBarsColorsNormalForeColor Value=&quot;#666666&quot; /&gt;
        ///    &lt;ScrollBarsColorsHoverBackColor Value=&quot;#CCCCCC&quot; /&gt;
        ///    &lt;ScrollBarsColorsHoverForeColor Value=&quot;#252526&quot; /&gt;
        ///    &lt;ScrollBarsColorsDisabledBackColor Value=&quot;#E6E6E6&quot; /&gt;
        ///    &lt;ScrollBarsColorsDisabledForeColor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string themesXml {
            get {
                return ResourceManager.GetString("themesXml", resourceCulture);
            }
        }
    }
}
