version: '{branch}.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
build:
  project: Yamui.Framework\Yamui.Framework.csproj
  verbosity: minimal
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false